[package]
name = "treegro"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.17.0"
egui-winit = "0.17.0"
egui_wgpu_backend = "0.17.0"
pixels = "0.9.0"
winit = "0.26.1"
winit_input_helper = "0.12.0"
